[package]
name = "s3ite"
version = "0.2.0"
edition = "2021"
description = "An S3 server backed by SQLite"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/seddonm1/s3ite"
keywords = ["s3", "sqlite"]
categories = ["database"]

[features]
default = ["binary"]
binary = ["tokio/full", "dep:clap", "dep:tracing-subscriber", "dep:hyper"]

[dependencies]
async-trait = "0.1.71"
base64-simd = "0.8.0"
bytes = "1.4.0"
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
clap = { version = "4.3.12", optional = true, features = ["derive"] }
deadpool-sqlite = { version = "0.5.0", default-features = false, features = ["rt_tokio_1"] }
rusqlite = { version = "0.28.0", features = ["time", "uuid", "bundled"] }
futures = "0.3.28"
hex-simd = "0.8.0"
hyper = { version = "0.14.27", optional = true, features = ["full"] }
md-5 = "0.10.5"
mime = "0.3.17"
nugine-rust-utils = "0.3.1"
numeric_cast = "0.2.1"
path-absolutize = "3.1.0"
s3s = "0.6.1"
serde = { version = "1.0.171", features =["derive"] }
serde_json = "1.0.103"
serde_yaml = "0.9.23"
thiserror = "1.0.43"
time = "0.3.23"
tokio = { version = "1.29.1", features = ["fs", "io-util"] }
tokio-util = { version = "0.7.8", features = ["io"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.1", features = ["cors"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.17", optional = true, features = ["env-filter", "time"] }
transform-stream = "0.3.0"
uuid = { version = "1.4.0", features = ["v4"] }

[dev-dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
aws-config = "0.55.3"
aws-credential-types = { version = "0.55.3", features = ["test-util"] }
aws-sdk-s3 = "0.28.0"
once_cell = "1.18.0"
s3s-aws =  "0.6.1"
tokio = { version = "1.29.1", features = ["full"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "time"] }

[profile.release]
codegen-units = 1
opt-level = 3
